language: python
python:
  - '3.7-dev'

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
  - 'flit install --symlink'

script: 'py.test --cov-report=xml --cov=./ tests/'

after_success:
  - codecov
